### PR TITLE
fix: patch ocha_snap module and revert unnecessary changes

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-9238

This reverts the changes in https://github.com/UN-OCHA/gms-site/pull/313/files and adds a patch for the ocha_snap module. Will make a PR to the module too.

### CODE REVIEW

**Review by cafuego — CHANGES_REQUESTED** [review]
Let's not patch the module but just do the upstream fix and then bump the version here.

**Comment by lazysoundsystem** [comment]
I'm fine with that - I made a PR for upstream https://github.com/UN-OCHA/ocha_snap/pull/14 - and can bump the module in this PR when that's released.

Checking that the patch actually works, first, though - there have been a couple of errors reported since it was reported, but I haven't managed to trigger it from those urls: https://elk.aws.ahconu.org/app/r/s/U6288

Blocking for the moment.

**Comment by cafuego** [comment]
Oh, yes if you want to check that it works then this is cool to merge and deploy :-)

**Review by cafuego — APPROVED** [review]

**Comment by lazysoundsystem** [comment]
I've created a new v8.6.0 release for ocha_snap - when that's updated on packagist, I'll redo this PR with the new version.

**Comment by lazysoundsystem** [comment]
This updates the ocha_snap module and reverts the earlier changes to the gms_pdflink module. Merging.

**Pull request merged**
